## Variables and Data
in Python

In [1]:
weight = 81

In [2]:
weight

81

In [3]:
print (weight)

81

In [4]:
# Import a dataset into Python
import pandas as pd

In [5]:
data = pd.read_csv('data/gapminder_all.csv')

In [7]:
type(data)

pandas.core.frame.DataFrame

In [9]:
#More about the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 38 columns):
continent         142 non-null object
country           142 non-null object
gdpPercap_1952    142 non-null float64
gdpPercap_1957    142 non-null float64
gdpPercap_1962    142 non-null float64
gdpPercap_1967    142 non-null float64
gdpPercap_1972    142 non-null float64
gdpPercap_1977    142 non-null float64
gdpPercap_1982    142 non-null float64
gdpPercap_1987    142 non-null float64
gdpPercap_1992    142 non-null float64
gdpPercap_1997    142 non-null float64
gdpPercap_2002    142 non-null float64
gdpPercap_2007    142 non-null float64
lifeExp_1952      142 non-null float64
lifeExp_1957      142 non-null float64
lifeExp_1962      142 non-null float64
lifeExp_1967      142 non-null float64
lifeExp_1972      142 non-null float64
lifeExp_1977      142 non-null float64
lifeExp_1982      142 non-null float64
lifeExp_1987      142 non-null float64
lifeExp_1992      142 non-null float64
lifeExp_1997      142 non-null float64
lifeExp_2002      142 non-null float64
lifeExp_2007      142 non-null float64
pop_1952          142 non-null float64
pop_1957          142 non-null float64
pop_1962          142 non-null float64
pop_1967          142 non-null float64
pop_1972          142 non-null float64
pop_1977          142 non-null float64
pop_1982          142 non-null float64
pop_1987          142 non-null float64
pop_1992          142 non-null float64
pop_1997          142 non-null float64
pop_2002          142 non-null int64
pop_2007          142 non-null int64
dtypes: float64(34), int64(2), object(2)
memory usage: 42.2+ KB

In [10]:
#What columns are there?
print (data.columns)

Index(['continent', 'country', 'gdpPercap_1952', 'gdpPercap_1957',
       'gdpPercap_1962', 'gdpPercap_1967', 'gdpPercap_1972', 'gdpPercap_1977',
       'gdpPercap_1982', 'gdpPercap_1987', 'gdpPercap_1992', 'gdpPercap_1997',
       'gdpPercap_2002', 'gdpPercap_2007', 'lifeExp_1952', 'lifeExp_1957',
       'lifeExp_1962', 'lifeExp_1967', 'lifeExp_1972', 'lifeExp_1977',
       'lifeExp_1982', 'lifeExp_1987', 'lifeExp_1992', 'lifeExp_1997',
       'lifeExp_2002', 'lifeExp_2007', 'pop_1952', 'pop_1957', 'pop_1962',
       'pop_1967', 'pop_1972', 'pop_1977', 'pop_1982', 'pop_1987', 'pop_1992',
       'pop_1997', 'pop_2002', 'pop_2007'],
      dtype='object')

In [11]:
#summary statistics
print (data.describe())

       gdpPercap_1952  gdpPercap_1957  gdpPercap_1962  gdpPercap_1967  \
count      142.000000      142.000000      142.000000      142.000000
mean      3725.276046     4299.408345     4725.812342     5483.653047
std       9321.064786     9869.662202     8667.362525     8095.315431
min        298.846212      335.997115      355.203227      349.000000
25%        864.752389      930.540819     1059.149171     1151.245103
50%       1968.528344     2173.220291     2335.439533     2678.334741
75%       3913.492777     4876.356362     5709.381428     7075.932943
max     108382.352900   113523.132900    95458.111760    80894.883260

       gdpPercap_1972  gdpPercap_1977  gdpPercap_1982  gdpPercap_1987  \
count      142.000000      142.000000      142.000000      142.000000
mean      6770.082815     7313.166421     7518.901673     7900.920218
std      10614.383403     8362.489150     7733.845006     8288.281304
min        357.000000      371.000000      424.000000      385.000000
25%       1257.193853     1357.257252     1363.338985     1327.469823
50%       3339.129407     3798.609244     4216.228428     4280.300366
75%       9508.839303    11204.102423    12347.953723    11994.052795
max     109347.867000    59265.477140    33693.175250    31540.974800

       gdpPercap_1992  gdpPercap_1997  ...      pop_1962      pop_1967  \
count      142.000000      142.000000  ...  1.420000e+02  1.420000e+02
mean      8158.608521     9090.175363  ...  2.042101e+07  2.265830e+07
std       9031.846080    10171.493263  ...  6.978865e+07  7.837548e+07
min        347.000000      312.188423  ...  6.534500e+04  7.078700e+04
25%       1270.660958     1366.837958  ...  1.784362e+06  2.034768e+06
50%       4386.085502     4781.825478  ...  4.686040e+06  5.170176e+06
75%      10684.351870    12022.867188  ...  1.098008e+07  1.261458e+07
max      34932.919590    41283.164330  ...  6.657700e+08  7.545500e+08

           pop_1972      pop_1977      pop_1982      pop_1987      pop_1992  \
count  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02  1.420000e+02
mean   2.518998e+07  2.767638e+07  3.020730e+07  3.303857e+07  3.599092e+07
std    8.864682e+07  9.748109e+07  1.050986e+08  1.147562e+08  1.245026e+08
min    7.659500e+04  8.679600e+04  9.859300e+04  1.108120e+05  1.259110e+05
25%    2.351192e+06  2.759717e+06  3.006286e+06  3.194990e+06  3.605992e+06
50%    5.877996e+06  6.404036e+06  7.007320e+06  7.774862e+06  8.688686e+06
75%    1.467920e+07  1.667023e+07  1.840732e+07  2.094754e+07  2.270538e+07
max    8.620300e+08  9.434550e+08  1.000281e+09  1.084035e+09  1.164970e+09

           pop_1997      pop_2002      pop_2007
count  1.420000e+02  1.420000e+02  1.420000e+02
mean   3.883947e+07  4.145759e+07  4.402122e+07
std    1.334174e+08  1.408483e+08  1.476214e+08
min    1.456080e+05  1.703720e+05  1.995790e+05
25%    3.770150e+06  4.173506e+06  4.508034e+06
50%    9.735064e+06  1.037292e+07  1.051753e+07
75%    2.431137e+07  2.654556e+07  3.121004e+07
max    1.230075e+09  1.280400e+09  1.318683e+09

[8 rows x 36 columns]

In [15]:
#Head and tail
data.head(3)

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
0,Africa,Algeria,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
1,Africa,Angola,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
2,Africa,Benin,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314

In [14]:
data.tail()

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
137,Europe,Switzerland,14734.232750,17909.489730,20431.092700,22966.144320,27195.11304,26982.290520,28397.715120,30281.704590,...,5666000.0,6063000.0,6401400.0,6316424.0,6468126.0,6649942.0,6995447.0,7193761.0,7361757,7554661
138,Europe,Turkey,1969.100980,2218.754257,2322.869908,2826.356387,3450.69638,4269.122326,4241.356344,5089.043686,...,29788695.0,33411317.0,37492953.0,42404033.0,47328791.0,52881328.0,58179144.0,63047647.0,67308928,71158647
139,Europe,United Kingdom,9979.508487,11283.177950,12477.177070,14142.850890,15895.11641,17428.748460,18232.424520,21664.787670,...,53292000.0,54959000.0,56079000.0,56179000.0,56339704.0,56981620.0,57866349.0,58808266.0,59912431,60776238
140,Oceania,Australia,10039.595640,10949.649590,12217.226860,14526.124650,16788.62948,18334.197510,19477.009280,21888.889030,...,10794968.0,11872264.0,13177000.0,14074100.0,15184200.0,16257249.0,17481977.0,18565243.0,19546792,20434176
141,Oceania,New Zealand,10556.575660,12247.395320,13175.678000,14463.918930,16046.03728,16233.717700,17632.410400,19007.191290,...,2488550.0,2728150.0,2929100.0,3164900.0,3210650.0,3317166.0,3437674.0,3676187.0,3908037,4115771